### ISSUE TITLE
Model Training.

### ISSUE THREAD

**Issue by Udit-git-acc** [ZeningLin/ViBERTgrid-PyTorch#16]
Sir, I was trying to run your code and found that weights are not being saved, I found that you have used a very high values of F1_score = 0.95. Can you please explain the reason of keeping such high value. Because during our testing we were getting the maximum F1 value of 0.4328 during validation. We used the SROIE dataset.  
 Also the maximum epochs were 33 then why have you used the condition of (epoch % 400 == 0) in file train_SROIE.py, line 364.
Thanks

**Comment by ZeningLin** [comment]
Hello,

As for the weights saving stuff, you can set the (epoch % 400 == 0) to smaller values like 10 to save weights at earlier steps (just a setting I used in earlier developments and I forgot to change it).  In my case, the model worked well and gave F1 values larger than 0.95, that's why I used took 0..95 as the treshold.

For the model training problem, I need more information. You can directly email me at zening.lin@outlook.com.

Best wishes,
Zening Lin

**Comment by ZeningLin** [comment]
Hello,

As for the weights saving stuff, you can set the (epoch % 400 == 0) to smaller values like 10 to save weights at earlier steps (just a setting I used in earlier developments and I forgot to change it).  In my case, the model worked well and gave F1 values larger than 0.95, that's why I used took 0..95 as the treshold.

For the model training problem, I need more information. You can directly email me at zening.lin@outlook.com.

Best wishes,
Zening Lin
