### ISSUE TITLE
For Inference Pre-trained weights are not available. Inference running giving errors. 

### ISSUE THREAD

**Issue by papiamahato** [ZeningLin/ViBERTgrid-PyTorch#19]
Inference running giving errors as pre-trained weights are not available.
Please provide the pre-trained weights.

**Comment by ZeningLin** [comment]
Hello,

Sorry for my late reply.

This project was done when I work as intern a long time ago, I am afraid that the weights saved in the server cannot be shared due to the company's limitations. I will re-train the model and generate the weights if I were free. You may also try to train the model by yourself.

**Comment by ZeningLin** [comment]
Hello,

A pre-trained weights is available at [google drive](https://drive.google.com/file/d/1VI5g9wbtc0uihhCmM3g5_g20UFVOGhw6/view?usp=sharing), see whether it works or not
